name: "Pullfrog Action"
description: "Execute coding agents with a prompt"
author: "Pullfrog"

inputs:
  prompt:
    description: "Prompt to send to the agent"
    required: true
  effort:
    description: "Effort level: nothink (fast), think (default), max (most capable)"
    required: false
    default: "think"

runs:
  using: "node24"
  main: "entry"

branding:
  icon: "code"
  color: "green"
