name: "Pullfrog Claude Code Action"
description: "Execute Claude Code with a prompt using Anthropic API"
author: "Pullfrog"

inputs:
  prompt:
    description: "Prompt to send to Claude Code"
    required: true
    default: "Hello from Claude Code!"
  anthropic_api_key:
    description: "Anthropic API key for Claude Code authentication"
    required: false
  github_token:
    description: "GitHub token for repository access"
    required: false
  github_installation_token:
    description: "GitHub App installation token"
    required: false

runs:
  using: "composite"
  steps:
    - name: Setup Node.js 24
      uses: actions/setup-node@v4
      with:
        node-version: "24"
    - name: Run TypeScript entry point
      run: node entry.ts
      shell: bash
      working-directory: ${{ github.action_path }}

branding:
  icon: "code"
  color: "orange"
