name: "Pullfrog Claude Code Action"
description: "Execute Claude Code with a prompt using Anthropic API"
author: "Pullfrog"

inputs:
  prompt:
    description: "Prompt to send to Claude Code"
    required: true
    default: "Hello from Claude Code!"
  defaultAgent:
    description: "Default agent to use. Overridden by payload.agent if present."
    required: false
    type: choice
    options:
      - claude
      - codex
      - cursor
      - gemini
  anthropic_api_key:
    description: "Anthropic API key for Claude Code authentication"
    required: false
  openai_api_key:
    description: "OpenAI API key for Codex authentication"
    required: false
  google_api_key:
    description: "Google API key for Jules authentication"
    required: false
  gemini_api_key:
    description: "Gemini API key for Jules authentication"
    required: false
  cursor_api_key:
    description: "Cursor API key for Cursor authentication"
    required: false

runs:
  using: "node20"
  main: "entry"

branding:
  icon: "code"
  color: "green"
